spring:
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/test
    username : root
    password : root
    schema : classpath:data.sql
    sql-script-encoding : utf-8
    initialSize : 5
    minIdle : 5
    maxActive : 20
    maxWait : 60000
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1 FROM DUAL
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxPoolPreparedStatementPerConnectionSize : 20
    filters : stat,wall,log4j
    connectionProperties :
      druid.stat.mergeSql : true
      druid.stat.slowSqlMillis : 5000
  redis:
    database : 0
    host : 106.14.199.40
    port : 6379
    password :
    timeout : 0
    pool:
      max-active : -1
      max-wait : -1
      max-idle : 8
      min-idle : 0